services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Root12345!
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: restauranteDB
      MYSQL_USER: appuser
      MYSQL_PASSWORD: App12345!
    ports:
      - "3308:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro

  backend:
    build: .
    environment:
      NODE_ENV: development
      PORT: 4000
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: appuser
      DB_PASSWORD: App12345!
      DB_NAME: restauranteDB
    depends_on:
      - db
    ports:
      - "4000:4000"
  
    volumes:
      - ./src:/app/src
      - ./public:/app/public

    command: ["node", "--watch", "src/index.js"]