### Autenticación
POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "email": "admin@restaurante.com",
  "password": "Admin123!"
}

### Listar unidades (público)
GET http://localhost:4000/api/units

### Crear ingrediente (ADMIN)
POST http://localhost:4000/api/ingredients
Content-Type: application/json

{
  "name": "Pechuga de pollo",
  "unit_id": 2,
  "stock_qty": 5000,
  "min_qty": 500
}

### Listar ingredientes (ADMIN)
GET http://localhost:4000/api/ingredients

### Crear PRODUCTO (ADMIN)
POST http://localhost:4000/api/menu-items
Content-Type: application/json

{
  "type": "PRODUCTO",
  "name": "Coca-Cola lata 355ml",
  "description": "Bebida gaseosa",
  "price": 8.50
}

### Crear PLATO (ADMIN)
POST http://localhost:4000/api/menu-items
Content-Type: application/json

{
  "type": "PLATO",
  "name": "Pollo a la plancha",
  "description": "Pechuga a la plancha",
  "price": 45.00
}

### Reemplazar receta del PLATO (ADMIN)
PUT http://localhost:4000/api/menu-items/2/recipe
Content-Type: application/json

{
  "ingredients": [
    { "ingredient_id": 1, "qty": 200 }
  ]
}

### Obtener receta del PLATO (ADMIN)
GET http://localhost:4000/api/menu-items/2/recipe

### Listado público del menú (activos)
GET http://localhost:4000/api/menu-items
GET http://localhost:4000/health

###
GET http://localhost:4000/db/ping

###
# Ping de reserva con payload de ejemplo (llama al SP)
GET http://localhost:4000/api/ping-reserva

###
# Crear reserva real
POST http://localhost:4000/api/reservas
Content-Type: application/json

{
  "mesas": "2,4",
  "fechaReservaISO": "2025-12-31T20:00:00.000Z",
  "duracionMin": 120,
  "cliente": { "nombre": "Ana Pérez", "dni": "87654321", "telefono": "555-1234", "email": "ana@correo.com" },
  "comensales": 4,
  "descuento": 0,
  "items": [
    { "id": 10, "tipo": "PLATO", "cantidad": 1 },
    { "id": "AGUA_500ML_QR006", "tipo": "PRODUCTO", "cantidad": 2 }
  ],
  "usuario": "mesero1"
}