GET http://localhost:4000/health

###
GET http://localhost:4000/db/ping

###
# Ping de reserva con payload de ejemplo (llama al SP)
GET http://localhost:4000/api/ping-reserva

###
# Crear reserva real
POST http://localhost:4000/api/reservas
Content-Type: application/json

{
  "mesas": "2,4",
  "fechaReservaISO": "2025-12-31T20:00:00.000Z",
  "duracionMin": 120,
  "cliente": { "nombre": "Ana Pérez", "dni": "87654321", "telefono": "555-1234", "email": "ana@correo.com" },
  "comensales": 4,
  "descuento": 0,
  "items": [
    { "id": 10, "tipo": "PLATO", "cantidad": 1 },
    { "id": "AGUA_500ML_QR006", "tipo": "PRODUCTO", "cantidad": 2 }
  ],
  "usuario": "mesero1"
}